version: '2'
services:
  servicenet-mongo:
    extends:
      file: mongo.yml
      service: servicenet-mongo
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader

  servicenetauth-app:
    image: servicenetauth
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      # You can find the host ip by running: "ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${HOST_IP}:5432/ServiceNet?currentSchema=auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - JHIPSTER_SLEEP=0 # gives time for other services to boot before the application
