version: '2'
services:
  servicenetgateway-app:
    image: servicenetgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servicenet-postgresql:5432/ServiceNetGateway
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  servicenet-app:
    image: servicenet
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servicenet-postgresql:5432/ServiceNet
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - SPRING_DATA_MONGODB_URI=mongodb://servicenet-mongo:27017/serviceNet
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  servicenet-postgresql:
    extends:
      file: postgresql.yml
      service: servicenet-postgresql
  consul:
    extends:
      file: consul.yml
      service: consul
  servicenet-mongo:
    extends:
      file: mongo.yml
      service: servicenet-mongo

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
